import React from 'react'
import Head from "next/head";
import MenuApp from "../../src/components/Menu";
import { Image } from '@mantine/core';
import { Space, Card ,Group, Badge ,Text} from '@mantine/core';


function test() {
  return (
    <div>
      <Head>
        <title>Front</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>

      <main>
      <Space h="md" />
      <MenuApp />
    
      <Space h="md" />
      
      <Card shadow="sm" radius="md" withBorder>
              <Card.Section>
                <Image
                  src="https://images.unsplash.com/photo-1627552245715-77d79bbf6fe2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=640&q=80"
                  height={200}
                  width={200}
                />
              </Card.Section>
        
              <Group position="apart" mt="md" mb="xs">
                <Badge color="green" variant="light">
                  disponible
                </Badge>
              </Group>
        
              <Text size="sm" color="dimmed">
                etage
              </Text>
              <Text size="sm" color="dimmed">
                num salle
              </Text>
              <Text size="sm" color="dimmed">
                num chaises
              </Text>
              <Text size="sm" color="dimmed">
                mico video projecteur..
              </Text>
              </Card>

</main>
    </div>
  )
}

export default test
