import React from 'react'
import Head from "next/head";
import MenuApp from "../../src/components/Menu";
import GridReservations from "../../src/components/gridReservations";
import { Space,Grid,Card,Group ,Badge,Button,Text,Image, Loader } from '@mantine/core';
import { useQuery, gql } from "@apollo/client";

const GET_RESERVATIONS =gql`
query Query {
  getReservations {

    date_heure
    etat
    user {
      id
      username
      password
      email
      isAdmin
      image
    }
    salle {
      id
      etage
      num_salle
      nbr_chaises
      acces_handicape
      micro
      video_projecteur
      sound_proof
      climatiseur
      image
    }
  }
}`;

export default function Reservation() {
  const { loading, error, data } = useQuery(GET_RESERVATIONS);
  if (error) return <p>Error: {error.message}</p>;
  const reservations = data?.getReservations;
  return (
    <div>
     <Head>
        <title>Front</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>

      <main >
        
        
      <Space h="md" />
      <MenuApp />

      <h2 style={{ textAlign: 'center' }}>List des reservations :</h2>
      {loading ? (
        <Loader/>
      ) : (
        <ul><Grid   gutterXl={25}>
        {reservations?.map((reservation) =>(

        <Grid.Col  md={6} lg={3} >
              <Card shadow="sm" padding="lg" radius="md" withBorder>
              
        
              <Group position="apart" mt="md" mb="xs">
                <Badge color={reservation.etat ? 'green' : 'red'} variant="light">
                    {reservation.etat ? 'reservé' : 'archive'}
                  </Badge>
                <Text size="sm" color="dimmed">
                {reservation.date_heure}
              </Text>
              </Group>
        
       
              <Card.Section>
                       <Image
                         src={reservation.salle.image}
                         height={160}
                         caption={"etage: "+reservation.salle.etage +" | "+"num salle:"+ reservation.salle.num_salle}
                       />
                     </Card.Section>
                     <Card.Section style={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }} >
                       <Image
                         src={reservation.user.image}
                         height={70}
                         width ={70}
                         
                         caption={reservation.user.username}
                       />
                     </Card.Section>
       
               
       
        
              <Button variant="light" color="blue" fullWidth mt="md" radius="md">
                plus..
              </Button>
            </Card>
       
            </Grid.Col>
        ))}
       
</Grid>    </ul> 
      )}   


      </main>
    </div>
  )
}