import { Image } from '@mantine/core';
import { Grid , Box ,Space } from '@mantine/core';
import Head from "next/head";
import MenuApp from "../src/components/Menu";
import { Text ,Button,Stack, Container, Input, PasswordInput} from '@mantine/core';
function Profile(){
    return(
    
      <div>
      <Head>
        <title>Front</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>

      <main >
      <Space h="md" />
      <MenuApp />



      <Image maw={450} mx="auto" radius="md" 
              src="https://images.unsplash.com/photo-1627552245715-77d79bbf6fe2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=640&q=80"
              alt="image"   />
<Space h="md" />
   
      <Container size="30rem" px={0}>
      <Input
      placeholder="Username"
    />
    <Input
      placeholder="Email"
    />
    <PasswordInput
      placeholder="Password"
    />
</Container>

    

    </main>
    </div>

    );
}
export default Profile;